version: '2.1'

services:

  base-app:
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV-development}
    command: yarn run start-watch
    environment:
      AS_API_KEY: ${AS_API_KEY}
      AS_INDEX: ${AS_INDEX}
      AS_SERVICE_NAME: ${AS_SERVICE_NAME}
      AS_VERSION: ${AS_VERSION}
      NODE_ENV: ${NODE_ENV-development}

  frontend:
    extends:
      service: base-app
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - node_modules:/code/node_modules
      - .:/code

volumes:
  node_modules:
